#!/usr/bin/env python3
"""Promote one T-613 clone-verified batch to primary with insert-only SQL.

This is intentionally separate from the earlier watchlist promoter.  It
accepts only T-613 batch plans, a campaign approval bound to the immutable
registry manifest, and two clone execution artifacts.  Manual-review reports
are copied as restricted local references with no invented citation evidence.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import sys
from typing import Any, Callable, Mapping

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.build_research_report_registry_decision import payload_sha256
from scripts import promote_research_report_clone_to_primary as base
from scripts.recover_watchlist_research_reports import BOUNDARY


TASK_ID = "T-619"
BATCH_PATTERN = re.compile(r"^t613-batch-00(?:0[6-9]|[1-3][0-9]|4[0-4])$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")


class BatchPromotionRefused(base.PromotionRefused):
    """Raised when the batch-specific primary promotion contract is closed."""


def _artifact(path: Path, *, label: str) -> tuple[dict[str, Any], str]:
    payload = base._load_json(path, label=label)
    return payload, base._file_sha256(path)


def _require_sha(value: Any, *, label: str) -> str:
    result = str(value or "")
    if not SHA256.fullmatch(result):
        raise BatchPromotionRefused(f"{label} must be a SHA-256 digest")
    return result


def _batch_entries(plan: Mapping[str, Any]) -> dict[str, dict[str, str]]:
    if plan.get("schema_version") != "research-report-clone-batch-plan-v1":
        raise BatchPromotionRefused("unsupported clone batch plan schema")
    if payload_sha256(dict(plan)) != plan.get("plan_sha256", payload_sha256(dict(plan))):
        # Plans generated by prepare_research_report_clone_batch do not carry
        # plan_sha256; preflight and execution artifacts bind the canonical hash.
        raise BatchPromotionRefused("embedded plan SHA-256 is invalid")
    batch_id = str(plan.get("batch_id") or "")
    if not BATCH_PATTERN.fullmatch(batch_id):
        raise BatchPromotionRefused("plan batch is outside the authorized 0006-0044 range")
    for key in ("manifest_sha256", "batch_sha256", "raw_content_identity_sha256", "backup_dump_sha256"):
        _require_sha(plan.get(key), label=f"plan.{key}")
    contract = plan.get("write_contract") if isinstance(plan.get("write_contract"), Mapping) else {}
    expected = {
        "target": "independently_attested_clone_only",
        "primary_writes_allowed": False,
        "insert_only": True,
        "updates_allowed": False,
        "deletes_allowed": False,
        "raw_files_preserved": True,
        "opensearch_preserved": True,
        "local_opinion_reference_only": True,
        "training_allowed": False,
        "broker_connected": False,
        "live_execution_allowed": False,
    }
    if any(contract.get(key) != value for key, value in expected.items()):
        raise BatchPromotionRefused("clone plan write contract changed")
    entries = plan.get("batch_entries") if isinstance(plan.get("batch_entries"), list) else []
    if not entries or len(entries) > 250:
        raise BatchPromotionRefused("batch must contain 1-250 entries")
    selected: dict[str, dict[str, str]] = {}
    documents: set[str] = set()
    content: set[str] = set()
    for raw in entries:
        if not isinstance(raw, Mapping):
            raise BatchPromotionRefused("batch entries must be objects")
        report_id, document_id, digest = (str(raw.get(key) or "") for key in ("report_id", "document_id", "content_sha256"))
        if (
            not base.SAFE_ID.fullmatch(report_id)
            or document_id != f"doc_{report_id}"
            or not SHA256.fullmatch(digest)
            or report_id in selected
            or document_id in documents
            or digest in content
            or str(raw.get("rights_policy_id") or "") != "local-research-reference-restricted-v1"
        ):
            raise BatchPromotionRefused("batch report/document/content identity is invalid or duplicate")
        selected[report_id] = {"report_id": report_id, "document_id": document_id, "content_sha256": digest}
        documents.add(document_id)
        content.add(digest)
    return selected


def _validate_campaign_approval(approval: Mapping[str, Any], *, plan: Mapping[str, Any]) -> None:
    if approval.get("schema_version") != "research-report-primary-campaign-approval-v1" or approval.get("status") != "approved":
        raise BatchPromotionRefused("primary campaign approval is unsupported or not approved")
    batch_id = str(plan["batch_id"])
    allowed = approval.get("authorized_batch_ids") if isinstance(approval.get("authorized_batch_ids"), list) else []
    expected = {
        "manifest_sha256": plan.get("manifest_sha256"),
        "primary_writes_allowed": True,
        "insert_only": True,
        "updates_allowed": False,
        "deletes_allowed": False,
        "raw_files_preserved": True,
        "duplicate_aliases_preserved": True,
        "opensearch_preserved": True,
        "local_opinion_reference_only": True,
        "training_allowed": False,
        "broker_connected": False,
        "live_execution_allowed": False,
    }
    if batch_id not in allowed or any(approval.get(key) != value for key, value in expected.items()):
        raise BatchPromotionRefused("primary campaign approval does not authorize this exact batch contract")


def _validate_independent_clone_attestation(
    attestation: Mapping[str, Any],
    *,
    attestation_plan: Mapping[str, Any],
    plan: Mapping[str, Any],
    source_snapshot: Mapping[str, Any],
    target_snapshot: Mapping[str, Any],
) -> dict[str, str]:
    """Bind an independently hosted source to its clone execution evidence.

    T-619 intentionally runs the clone in a separate PostgreSQL container.  A
    matching system identifier is therefore the wrong safety criterion: it
    would reject the isolated topology that the execution contract requires.
    This validator replaces that criterion with immutable attestation, plan,
    and live source-identity bindings.
    """

    identity = attestation.get("runtime_identity") if isinstance(attestation.get("runtime_identity"), Mapping) else {}
    proof = attestation.get("runtime_proof") if isinstance(attestation.get("runtime_proof"), Mapping) else {}
    evidence = attestation_plan.get("input_evidence") if isinstance(attestation_plan.get("input_evidence"), Mapping) else {}
    required_runtime = {
        "database_oid": str(source_snapshot["identity"]["database_oid"]),
        "postgres_system_identifier": str(source_snapshot["identity"]["postgres_system_identifier"]),
    }
    checks = {
        "attestation_schema": attestation.get("schema_version") == "research-report-clone-attestation-v1",
        "attestation_passed": attestation.get("status") == "passed",
        "attestation_clone_database": attestation.get("database_name") == source_snapshot["identity"]["database_name"]
        and attestation.get("runtime_database_name") == source_snapshot["identity"]["database_name"],
        "attestation_execution_isolated": attestation.get("execution_scope") == "inside_clone_app_container"
        and attestation.get("network_isolation") is True
        and attestation.get("raw_mount_read_only") is True
        and attestation.get("primary_service_reachable") is False
        and attestation.get("restore_verified") is True,
        "attestation_local_backends": attestation.get("object_store_backend") == "local"
        and attestation.get("search_backend") == "local",
        "attestation_runtime_hash": bool(proof)
        and attestation.get("runtime_proof_sha256") == payload_sha256(dict(proof)),
        "attestation_runtime_identity": all(str(identity.get(key) or "") == value for key, value in required_runtime.items()),
        "attestation_plan_binding": attestation.get("plan_sha256") == attestation_plan.get("plan_sha256")
        and attestation.get("source_backup_dump_sha256") == plan.get("backup_dump_sha256")
        and evidence.get("backup_dump_sha256") == plan.get("backup_dump_sha256"),
        "attestation_distinct_postgres": source_snapshot["identity"]["postgres_system_identifier"]
        != target_snapshot["identity"]["postgres_system_identifier"],
    }
    failed = [name for name, passed in checks.items() if not passed]
    if failed:
        raise BatchPromotionRefused(f"independent clone attestation failed: {','.join(failed)}")
    return {
        "attestation_plan_sha256": str(attestation_plan["plan_sha256"]),
        "runtime_postgres_system_identifier": str(identity["postgres_system_identifier"]),
        "runtime_database_oid": str(identity["database_oid"]),
    }


def _validate_run(
    payload: Mapping[str, Any], *, label: str, plan_sha256: str, plan: Mapping[str, Any], selected: Mapping[str, Mapping[str, str]], created: bool, prior_sha: str | None = None
) -> dict[str, dict[str, Any]]:
    if payload.get("schema_version") != "research-report-clone-batch-execution-v1" or payload.get("status") != "passed":
        raise BatchPromotionRefused(f"{label} did not pass")
    for key in ("plan_sha256", "manifest_sha256", "batch_id", "batch_sha256"):
        expected = plan_sha256 if key == "plan_sha256" else plan.get(key)
        if payload.get(key) != expected:
            raise BatchPromotionRefused(f"{label} is not bound to the supplied plan")
    checks = (
        payload.get("primary_writes_allowed") is False,
        payload.get("raw_files_preserved") is True,
        payload.get("opensearch_index_preserved") is True,
        not list(payload.get("delete_operations") or []),
        payload.get("fact_opinion_boundary") == BOUNDARY,
        int(payload.get("selected_report_count", -1)) == len(selected),
        int(payload.get("processed_count", -1)) == len(selected),
        int(payload.get("failed_count", -1)) == 0,
        int(payload.get("content_identity_verified_count", -1)) == len(selected),
        not list(payload.get("errors") or []),
    )
    if not all(checks):
        raise BatchPromotionRefused(f"{label} failed its preservation or completeness gates")
    artifact_core = dict(payload)
    artifact_sha = str(artifact_core.pop("artifact_sha256", ""))
    if not SHA256.fullmatch(artifact_sha) or payload_sha256(artifact_core) != artifact_sha:
        raise BatchPromotionRefused(f"{label} artifact SHA-256 is invalid")
    rows = payload.get("results") if isinstance(payload.get("results"), list) else []
    by_id: dict[str, dict[str, Any]] = {}
    for raw in rows:
        if not isinstance(raw, Mapping):
            raise BatchPromotionRefused(f"{label} results must be objects")
        row = dict(raw)
        report_id = str(row.get("report_id") or "")
        expected = selected.get(report_id)
        if expected is None or report_id in by_id:
            raise BatchPromotionRefused(f"{label} has an unexpected or duplicate report")
        evidence_count = int(row.get("evidence_count") or 0)
        text_indexed = row.get("status") == "text_indexed" and row.get("manual_review") is False and evidence_count > 0
        needs_review = row.get("status") == "needs_text_review" and row.get("manual_review") is True and evidence_count == 0
        if not (
            row.get("document_id") == expected["document_id"]
            and row.get("content_sha256") == expected["content_sha256"]
            and row.get("content_identity_verified") is True
            and bool(row.get("text_source"))
            and (text_indexed or needs_review)
            and row.get("ingest_created") is created
        ):
            raise BatchPromotionRefused(f"{label} strict report gate failed for {report_id}")
        by_id[report_id] = row
    if set(by_id) != set(selected) or int(payload.get("evidence_count") or -1) != sum(int(row["evidence_count"]) for row in by_id.values()):
        raise BatchPromotionRefused(f"{label} result totals differ from the selected batch")
    if prior_sha is not None:
        idem = payload.get("idempotency_comparison") if isinstance(payload.get("idempotency_comparison"), Mapping) else {}
        if idem.get("passed") is not True or idem.get("prior_run_sha256") != prior_sha:
            raise BatchPromotionRefused("run2 idempotency comparison is not bound to run1")
    return by_id


def _validate_slice(rows: list[dict[str, Any]], *, selected: Mapping[str, Mapping[str, str]], run2: Mapping[str, Mapping[str, Any]]) -> dict[str, Any]:
    by_key = {(row["collection"], row["item_id"]): row for row in rows}
    if len(by_key) != len(rows) or any(row["collection"] not in base.ALLOWED_COLLECTIONS for row in rows):
        raise BatchPromotionRefused("source slice is duplicate or outside the collection allowlist")
    source_ids: set[str] = set()
    citations: dict[str, list[dict[str, Any]]] = {item["document_id"]: [] for item in selected.values()}
    for report_id, expected in selected.items():
        report = by_key.get(("research_reports", report_id), {}).get("payload", {})
        document = by_key.get(("documents", expected["document_id"]), {}).get("payload", {})
        source_id = str(report.get("source_id") or "")
        if not (
            source_id and report.get("report_id") == report_id and report.get("document_id") == expected["document_id"]
            and report.get("content_sha256") == expected["content_sha256"] and report.get("status") == run2[report_id]["status"]
            and document.get("document_id") == expected["document_id"] and document.get("source_id") == source_id
            and document.get("document_type") == "research" and document.get("source_type") == "local_reference"
            and document.get("source_uri") == f"research-report://{report_id}" and document.get("content_sha256") == expected["content_sha256"]
            and base._rights_are_restricted(report) and base._rights_are_restricted(document)
        ):
            raise BatchPromotionRefused(f"source content/rights boundary failed for {report_id}")
        if run2[report_id]["status"] == "text_indexed" and not str(document.get("body") or "").strip():
            raise BatchPromotionRefused(f"text-indexed document is empty for {report_id}")
        source_ids.add(source_id)
    for row in rows:
        if row["collection"] != "evidence":
            continue
        payload, document_id = row["payload"], str(row["payload"].get("document_id") or "")
        if document_id not in citations or not (
            payload.get("evidence_id") == row["item_id"] and payload.get("section") == "research_report_citation"
            and str(payload.get("bbox") or "").startswith(f"research_report://{document_id};chunk=")
            and str(payload.get("span_text") or "").strip() and str(payload.get("canonical_text") or "").strip()
        ):
            raise BatchPromotionRefused("citation evidence escaped its approved document boundary")
        citations[document_id].append(row)
    for report_id, expected in selected.items():
        if len(citations[expected["document_id"]]) != int(run2[report_id]["evidence_count"]):
            raise BatchPromotionRefused(f"clone citation cardinality differs for {report_id}")
    actual_sources = {row["item_id"] for row in rows if row["collection"] == "sources"}
    if actual_sources != source_ids:
        raise BatchPromotionRefused("source definitions are not exactly bounded to selected reports")
    for source_id in actual_sources:
        source = by_key[("sources", source_id)]["payload"]
        if not (source.get("source_id") == source_id and source.get("source_type") == "local_reference" and base._rights_are_restricted(source)):
            raise BatchPromotionRefused("source definition rights boundary failed")
    counts = {key: sum(row["collection"] == key for row in rows) for key in base.ALLOWED_COLLECTIONS}
    return {"counts": counts, "slice_sha256": base._payload_sha256(rows)}


def _quiescence_core(snapshot: Mapping[str, Any], backup: Mapping[str, Any], writers: list[dict[str, Any]], now: datetime) -> dict[str, Any]:
    return {
        "schema_version": "research-report-primary-batch-quiescence-proof-v1", "producer": Path(__file__).name,
        "generated_at": now.isoformat(), "target_database": base.PRIMARY_DATABASE,
        "target_database_identity": dict(snapshot["identity"]), "target_table_counts": dict(snapshot["table_counts"]),
        "target_research_counts": dict(snapshot["research_counts"]), "target_backup_dump_sha256": backup["dump_sha256"],
        "other_database_sessions": 0, "writer_containers": writers,
        "operator_boundary": "primary_app_and_all_known_schedulers_stopped_for_t619_batch_promotion",
    }


def create_quiescence_proof(*, target_dsn: str, target_backup_path: Path, writer_containers: list[str], connect: Callable[[str], Any] | None = None, now: datetime | None = None) -> dict[str, Any]:
    connect, now = connect or base._default_connect, now or datetime.now(timezone.utc)
    if base._database_name(target_dsn) != base.PRIMARY_DATABASE:
        raise BatchPromotionRefused("quiescence target must be ai_quant")
    manifest, _ = _artifact(target_backup_path, label="target backup")
    snapshot = base._read_snapshot(target_dsn, connect=connect)
    backup = base._validate_backup_manifest(target_backup_path, manifest, snapshot=snapshot, expected_database=base.PRIMARY_DATABASE, now=now)
    if snapshot["other_database_sessions"] != 0:
        raise BatchPromotionRefused("primary database has active sessions")
    writers = base._inspect_writer_containers(writer_containers)
    core = _quiescence_core(snapshot, backup, writers, now)
    return {**core, "status": "passed", "proof_sha256": base._payload_sha256(core), "classification": "local-only", "acceptable_for_non_local_release": False}


def _validate_quiescence(proof: Mapping[str, Any], *, snapshot: Mapping[str, Any], backup: Mapping[str, Any], now: datetime) -> dict[str, str]:
    keys = tuple(_quiescence_core(snapshot, backup, [], now).keys())
    core = {key: proof.get(key) for key in keys}
    if proof.get("status") != "passed" or proof.get("producer") != Path(__file__).name or proof.get("proof_sha256") != base._payload_sha256(core):
        raise BatchPromotionRefused("batch quiescence proof is invalid")
    base._recent(proof.get("generated_at"), field_name="quiescence.generated_at", max_age=base.QUIESCENCE_MAX_AGE, now=now)
    base._validate_writer_rows(proof.get("writer_containers"))
    if not (
        proof.get("target_database") == base.PRIMARY_DATABASE and dict(proof.get("target_database_identity") or {}) == dict(snapshot["identity"])
        and dict(proof.get("target_table_counts") or {}) == dict(snapshot["table_counts"]) and dict(proof.get("target_research_counts") or {}) == dict(snapshot["research_counts"])
        and proof.get("target_backup_dump_sha256") == backup["dump_sha256"] and proof.get("other_database_sessions") == 0 and snapshot["other_database_sessions"] == 0
        and proof.get("operator_boundary") == "primary_app_and_all_known_schedulers_stopped_for_t619_batch_promotion"
    ):
        raise BatchPromotionRefused("batch quiescence proof no longer matches primary")
    return {"proof_sha256": str(proof["proof_sha256"]), "generated_at": str(proof["generated_at"])}


def prepare_promotion(*, source_dsn: str, target_dsn: str, plan_path: Path, run1_path: Path, run2_path: Path, campaign_approval_path: Path, clone_attestation_path: Path, clone_attestation_plan_path: Path, source_backup_path: Path, target_backup_path: Path, quiescence_proof_path: Path, connect: Callable[[str], Any] | None = None, now: datetime | None = None) -> dict[str, Any]:
    connect, now = connect or base._default_connect, now or datetime.now(timezone.utc)
    source_db, target_db = base._database_name(source_dsn), base._database_name(target_dsn)
    if target_db != base.PRIMARY_DATABASE or source_db == base.PRIMARY_DATABASE or not re.search(r"(?:clone|pilot|restore|test)", source_db):
        raise BatchPromotionRefused("source must be an explicit clone and target must be ai_quant")
    plan, plan_file_sha = _artifact(plan_path, label="batch plan")
    approval, approval_sha = _artifact(campaign_approval_path, label="campaign approval")
    run1_payload, run1_sha = _artifact(run1_path, label="clone run1")
    run2_payload, run2_sha = _artifact(run2_path, label="clone run2")
    clone_attestation, clone_attestation_sha = _artifact(clone_attestation_path, label="clone attestation")
    clone_attestation_plan, clone_attestation_plan_sha = _artifact(clone_attestation_plan_path, label="clone attestation plan")
    source_manifest, source_backup_sha = _artifact(source_backup_path, label="clone backup")
    target_manifest, target_backup_sha = _artifact(target_backup_path, label="primary backup")
    proof, proof_file_sha = _artifact(quiescence_proof_path, label="quiescence proof")
    selected = _batch_entries(plan)
    plan_sha = payload_sha256(plan)
    _validate_campaign_approval(approval, plan=plan)
    run1 = _validate_run(run1_payload, label="run1", plan_sha256=plan_sha, plan=plan, selected=selected, created=True)
    run2 = _validate_run(run2_payload, label="run2", plan_sha256=plan_sha, plan=plan, selected=selected, created=False, prior_sha=str(run1_payload["artifact_sha256"]))
    source_snapshot, source_rows = base._read_source_context(source_dsn, selected=selected, connect=connect)
    target_snapshot, target_rows = base._read_target_context(target_dsn, keys=base._record_keys(source_rows), connect=connect)
    same_postgres_instance = (
        source_snapshot["identity"]["postgres_system_identifier"]
        == target_snapshot["identity"]["postgres_system_identifier"]
    )
    if (
        source_snapshot["identity"]["database_name"] != source_db
        or target_snapshot["identity"]["database_name"] != target_db
        or (same_postgres_instance and source_snapshot["identity"]["database_oid"] == target_snapshot["identity"]["database_oid"])
        or source_snapshot["other_database_sessions"] != 0
        or target_snapshot["other_database_sessions"] != 0
    ):
        raise BatchPromotionRefused("runtime clone/primary identities or session quiescence are unsafe")
    independent_clone = _validate_independent_clone_attestation(
        clone_attestation,
        attestation_plan=clone_attestation_plan,
        plan=plan,
        source_snapshot=source_snapshot,
        target_snapshot=target_snapshot,
    )
    source_backup = base._validate_backup_manifest(source_backup_path, source_manifest, snapshot=source_snapshot, expected_database=source_db, now=now)
    target_backup = base._validate_backup_manifest(target_backup_path, target_manifest, snapshot=target_snapshot, expected_database=target_db, now=now)
    quiescence = _validate_quiescence(proof, snapshot=target_snapshot, backup=target_backup, now=now)
    slice_info = _validate_slice(source_rows, selected=selected, run2=run2)
    context: dict[str, Any] = {
        "source_database": source_db, "target_database": target_db, "source_dsn_redacted": base._redact_dsn(source_dsn), "target_dsn_redacted": base._redact_dsn(target_dsn),
        "source_snapshot": source_snapshot, "target_snapshot": target_snapshot, "source_backup": source_backup, "target_backup": target_backup, "quiescence": quiescence,
        "plan_sha256": plan_sha, "selected": selected, "source_rows": source_rows, "target_rows": target_rows, "slice": slice_info, "target_diff": base._target_diff(source_rows, target_rows),
        "independent_clone": independent_clone,
        "artifact_hashes": {"plan": plan_file_sha, "campaign_approval": approval_sha, "run1": run1_sha, "run2": run2_sha, "clone_attestation": clone_attestation_sha, "clone_attestation_plan": clone_attestation_plan_sha, "source_backup_manifest": source_backup_sha, "target_backup_manifest": target_backup_sha, "quiescence_proof_file": proof_file_sha},
        "batch_id": plan["batch_id"], "batch_sha256": plan["batch_sha256"], "manifest_sha256": plan["manifest_sha256"],
    }
    context["audit_event"] = {"event_id": f"evt_t619_{base._payload_sha256({'batch': plan['batch_sha256'], 'slice': slice_info['slice_sha256']})[:32]}", "actor": "t619_batch_primary_promotion", "action": "promote_research_report_clone_batch", "resource_type": "research_report_recovery_batch", "resource_id": f"{plan['batch_id']}:{slice_info['slice_sha256'][:24]}", "source": "postgres_clone_insert_only", "version": "t619-v1", "model_version": "", "prompt_version": "", "approval_state": "user_authorized_batch_campaign_insert_only", "trace_id": f"t619:{plan_sha[:24]}", "timestamp": base._parse_time(run2_payload["generated_at"], field_name="run2.generated_at").isoformat()}
    core = {key: context[key] for key in ("batch_id", "batch_sha256", "manifest_sha256", "plan_sha256", "source_snapshot", "target_snapshot", "source_backup", "target_backup", "quiescence", "independent_clone", "slice", "target_diff", "artifact_hashes")}
    context["required_confirmation"] = f"T619_PROMOTE:{base._payload_sha256(core)}"
    return context


def _public(context: Mapping[str, Any], *, mode: str, executed: bool = False) -> dict[str, Any]:
    return {"schema_version": "research-report-primary-batch-promotion-v1", "status": "completed" if executed else "ready", "mode": mode, "executed": executed, "task_id": TASK_ID, "batch_id": context["batch_id"], "batch_sha256": context["batch_sha256"], "manifest_sha256": context["manifest_sha256"], "source_database": context["source_database"], "target_database": context["target_database"], "plan_sha256": context["plan_sha256"], "selected_report_count": len(context["selected"]), "slice_sha256": context["slice"]["slice_sha256"], "slice_counts": context["slice"]["counts"], "insert_counts": context["target_diff"]["insert_counts"], "equal_existing_counts": context["target_diff"]["equal_counts"], "artifact_hashes": context["artifact_hashes"], "quiescence_proof_sha256": context["quiescence"]["proof_sha256"], "write_contract": {"strategy": "single_target_transaction_insert_only", "delete_operations": [], "update_operations": [], "raw_files_preserved": True, "duplicate_aliases_preserved": True, "opensearch_preserved": True, "fact_opinion_boundary": BOUNDARY, "real_broker_or_order_execution": False}, "required_confirmation": "consumed_and_redacted" if executed else context["required_confirmation"], "classification": "local-only", "acceptable_for_non_local_release": False}


def promote(**kwargs: Any) -> dict[str, Any]:
    confirm = str(kwargs.pop("confirm", ""))
    context = prepare_promotion(**kwargs)
    if confirm != context["required_confirmation"]:
        raise BatchPromotionRefused("--confirm must match the current batch preflight")
    transaction = base._insert_slice_transaction(kwargs["target_dsn"], context=context, connect=kwargs.get("connect") or base._default_connect)
    verification = base._post_commit_verify(kwargs["target_dsn"], context=context, transaction_result=transaction, connect=kwargs.get("connect") or base._default_connect)
    result = _public(context, mode="promote", executed=True)
    result["inserted_counts"] = {name: sum(key[0] == name for key in transaction["inserted_keys"]) for name in base.ALLOWED_COLLECTIONS}
    result["audit_inserted"] = bool(transaction["audit_inserted"])
    result["post_commit_verification"] = verification
    return result


def _dsn(name: str) -> str:
    return base._dsn_from_env(name)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=("preflight", "prove-quiescence", "promote"), default="preflight")
    parser.add_argument("--source-dsn-env", default="AI_QUANT_T619_SOURCE_DSN")
    parser.add_argument("--target-dsn-env", default="AI_QUANT_POSTGRES_DSN")
    parser.add_argument("--plan", type=Path); parser.add_argument("--run1", type=Path); parser.add_argument("--run2", type=Path); parser.add_argument("--campaign-approval", type=Path); parser.add_argument("--clone-attestation", type=Path); parser.add_argument("--clone-attestation-plan", type=Path)
    parser.add_argument("--source-backup", type=Path); parser.add_argument("--target-backup", type=Path); parser.add_argument("--quiescence-proof", type=Path); parser.add_argument("--writer-container", action="append", default=[]); parser.add_argument("--confirm", default=""); parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv); target_dsn = _dsn(args.target_dsn_env)
    if args.mode == "prove-quiescence":
        if args.target_backup is None: raise BatchPromotionRefused("--target-backup is required")
        result = create_quiescence_proof(target_dsn=target_dsn, target_backup_path=args.target_backup, writer_containers=args.writer_container)
    else:
        values = (args.plan, args.run1, args.run2, args.campaign_approval, args.clone_attestation, args.clone_attestation_plan, args.source_backup, args.target_backup, args.quiescence_proof)
        if any(value is None for value in values): raise BatchPromotionRefused("plan, runs, approval, clone attestation, backups, and proof are required")
        kwargs = {"source_dsn": _dsn(args.source_dsn_env), "target_dsn": target_dsn, "plan_path": args.plan, "run1_path": args.run1, "run2_path": args.run2, "campaign_approval_path": args.campaign_approval, "clone_attestation_path": args.clone_attestation, "clone_attestation_plan_path": args.clone_attestation_plan, "source_backup_path": args.source_backup, "target_backup_path": args.target_backup, "quiescence_proof_path": args.quiescence_proof}
        result = promote(**kwargs, confirm=args.confirm) if args.mode == "promote" else _public(prepare_promotion(**kwargs), mode="preflight")
    args.output.parent.mkdir(parents=True, exist_ok=True); args.output.write_text(base._canonical_json(result) + "\n", encoding="utf-8"); print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True)); return 0


if __name__ == "__main__":
    try: raise SystemExit(main())
    except base.PromotionRefused as exc: raise SystemExit(f"T-619 promotion refused: {exc}") from exc
